# Generated by Django 2.2.4 on 2019-09-17 01:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps', models.URLField()),
                ('job_role', models.CharField(max_length=48)),
                ('job_start_date', models.DateField()),
                ('job_pay_rate', models.FloatField()),
                ('job_pay_period', models.CharField(max_length=48)),
                ('job_desc', models.TextField(max_length=320)),
                ('job_status', models.CharField(choices=[('<i class="fas fa-hourglass-end mr-2 text-success fa-lg"></i>', 'Pending Agreement'), ('<i class="far fa-check-circle mr-2 text-success fa-lg"></i>', 'Available'), ('<i class="far fa-times-circle mr-2 text-secondary fa-lg"></i>', 'Filled'), ('<i class="far fa-check-circle mr-2 text-warning fa-lg"></i>', 'Partially Filled'), ('<i class="fas fa-calendar-times mr-2 text-danger fa-lg"></i>', 'Expired')], default='Available', max_length=180)),
                ('job_created', models.DateField(default=datetime.date.today)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
