# Generated by Django 2.2.4 on 2019-09-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='speciality',
            new_name='sector',
        ),
    ]
