# Generated by Django 2.2.4 on 2019-09-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190920_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.DecimalField(choices=[(0, ''), (1, 'Demi Chef'), (2, 'CDP  Chef'), (3, 'Sous Chef'), (4, 'Head Chef'), (5, 'Exec Chef')], decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.DecimalField(choices=[(0, ''), (10, 'Institution Chef'), (12, 'Banqueting Chef'), (20, 'Pub Chef'), (25, 'GastroPub Chef'), (35, 'Fine Dining Level Chef'), (50, 'Rosette Level Chef'), (80, 'Michelin Level Chef')], decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='years',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40)], decimal_places=0, default=0, max_digits=2),
        ),
    ]
